language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 2.0
- 2.1
- 2.2
- 2.3.0
- 2.4.1
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-golang.gemspec
- gem install sensu-plugins-golang-*.gem
deploy:
  provider: rubygems
  api_key:
    secure: Z32UELgIeTzGcGZvjX/KS6Q0ixymwPx37k5mE4mUGRZaFHLy1DQur7mgPXAKb+NYvsabHAIGtvf0UVQSABhn7iju1xKS2V3U7B7dg5x5C3/ZuPasRTb7+Z0BKHHXqlMZNymZzKMUAUZ+Kq1UOUBEVahs735ckm6/MMRQp31PfoM=
  gem: sensu-plugins-golang
  on:
    tags: true
    all_branches: true
    rvm: 1.9.3
    rvm: 2.0
    rvm: 2.1
    rvm: 2.2
    rvm: 2.3.0
    rvm: 2.4.1
    repo: sensu-plugins/sensu-plugins-golang
